### PR TITLE
Pull the file path as well

### PR DESCRIPTION
**Pull request by Rudd-O**
Useful for automating a number of things, like creating playlists based on what is playing right now.

### CODE REVIEW

**Comment by Rudd-O** [comment]
Whoa, thank you, you rock!  This is gonna help me drop a ton of cruft in my Node-RED drawing board.

**Comment by jtbgroup** [comment]
Done in version 3.6.0.
I'm really curious to know what you all do in Node red with this integration :-)

**Comment by Rudd-O** [comment]
It's super straightforward — I use this bit of information from the currently playing element to add to my favorites of the month playlist (I have a "button" I push for that) using a small REST service to manage playlists that runs in my HTPC.  These monthly playlists then get later synced to my phone for on-the-road music.

**Comment by Rudd-O** [comment]
Found another corner case which I fixed here: https://github.com/jtbgroup/kodi-media-sensors/pull/23

**Pull request merged**
