### PR TITLE
Add: Channels search

### PR DESCRIPTION
**Pull request by JurajNyiri**
Hey,

I am author of https://github.com/JurajNyiri/PlexMeetsHomeAssistant where I am using your integration to easily search TV Shows / Movies and play it from Plex on Kodi.

Recently, I am adding Live TV and I noticed your integration is missing ability to search in channels, so I added it.

Unfortunately, JSON RPC from Kodi does not support filter on PVR.GetChannels nor has any function to search channels. So I have chosen to get all the channels and filter them out.

Let me know if any adjustments are needed and/or please feel free to take the code and modify it.

### CODE REVIEW

**Comment by jtbgroup** [comment]
Hi,

Sorry for my late answer, I don't check often my messages on Github...

Great to hear someone else uses my integration :-). I recently changed a lot in the integration (mainly the playlist sensor), so I have to check if your code still remains compatible with the last one, but as far as I could see, there should be no problem. I also need a couple of days to integrate, build and test (I'm not familiar at all with pull requests...!)

Juste a question beside. I tried to install the version 3.0.1 on a the home assistant of a friend and it seemed buggy while I have no problem on my installation. did ou notice something special? (especially with the sensor playlist which stayed off all the time)

**Comment by JurajNyiri** [comment]
@jtbgroup glad to hear that we can merge this soon! 👍 If you have troubles merging it just copy the relevant parts of the code and feel free to close this PR!
Unfortunately I cannot help you with the playlist sensor as I am not using it, I am just using it with the search service and getting the results from attribute of the search sensor, thats all.

**Comment by jtbgroup** [comment]
Hi, 
I just tested directly a json request, but calling the PVR.GetChannels returns me 'Failed to execute method'. 
Not a good idea to implement it like that... :-)

I suppose it's because I do not have a PVR functionality in Kodi? Do you know a way to test it before the calling this method?

**Comment by jtbgroup** [comment]
Hello,

just tested, but unfortunately, the exception is already catched before and not propagated. The result returned is None. So difficult to know if your kodi has a PVR capability. 

Keeping the pvr ability in a variable would mean you need to restart your integration if you change your kodi configuration. This is not intuitive and would generate errors if you disable the pvr. I think the pvr query is needed for each search, but you have to deal with the error. It seems we are not the first one :-)
https://forum.kodi.tv/showthread.php?tid=349115

As i did some modification on the develop branch, I created a new one called 'pvr' wich is merged with the latest code https://github.com/jtbgroup/kodi-media-sensors/tree/pvr

**Comment by JurajNyiri** [comment]
Hey @jtbgroup!

Anything I can do here to help merge this in?

Thank you!

**Comment by jtbgroup** [comment]
Hi,

I've been busy with other functionalities. I still have to find the best approach to deal with PVR. If you know the error codes of kodi, it would be fine. 

Can you also give me a plugin to test the PVR functionality in Kodi?

**Comment by jtbgroup** [comment]
Hello,

I did some changes in the code to integrate the PVR search functionality. A new version is available in beta on HACS. I need a little time to check if the code is stable for production, but you can already test it. Don't forget to update the cards also. 

Can you give feedback, please? (and if it works, send some screenshots as I don't use a PVR client addon)

**Comment by jtbgroup** [comment]
Hi, thanks for your reply. I'll probably check the code this evening and propose a new beta version.

**Comment by jtbgroup** [comment]
Adding the boolean parameter would not do what I want as I use the limit property.

First, you can also search in the file **/config/.storage/core.config_entries* if you find the option called *search_channels_limit*.

Then, you can also check in the config in the integration if you have a value  for the search limit of the channels?

Screenshot_20211206_180346

Opening it might add the limit option. This wouldn't explain why the default value of this limit is not used.

**Comment by JurajNyiri** [comment]
I am a bit confused. I pulled the latest https://github.com/jtbgroup/kodi-media-sensors/tree/develop branch, is that correct?

What I am saying is that if we want to _search_ on channels, we need to get all the channels - without limit set to anything. Otherwise the search will always return an empty array on channels that are outside of default limit range if we search for something at the end of alphabet, like in the case I described above - VH1.

**Comment by jtbgroup** [comment]
Yes, it's this branch.
ok, understood. you're right! That's the inconvenient of developing something without being able to test it.
I like the limit option to reduce the memory footprint in HA. What I will probably to is 
- remove the limit if the option == 0 (for all the types)
- limit the channels after filter if needed
I know what to do this evening

**Comment by jtbgroup** [comment]
just pushed a new beta release. 
For channels, limits are now applied after the filter. Setting limit to 0 will not limit the resultset. I also do 2 separate search for channels (tv and radio).

**Comment by JurajNyiri** [comment]
Works as expected now! 💯

**Pull request closed without merging**
